name: 'Publish application'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET daily build .NET 6
          run: |
            wget -O ./dotnet-install.sh https://dot.net/v1/dotnet-install.sh
            echo $PATH
            ls -l
            sudo ./dotnet-install.sh -Channel release/6.0.1xx-preview5 -InstallDir dotnet
            sudo which dotnet
        
        # Add Nuget.Config to solution
        - name: Install Nuget configs
          run: |
            dotnet new nugetconfig
            dotnet nuget add source -n dotnet6 https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet6/nuget/v3/index.json
        
        # Added Ahead-Of-Time workload
        - name: Add AOT Workload
          run: dotnet workload install microsoft-net-sdk-blazorwebassembly-aot 2>&1 | tee log

        # Run tests
        - name: Test
          run: dotnet test

        # Generate the website
        - name: Publish
          run: dotnet publish samples/KristofferStrube.Blazor.SVGEditor.Samples/KristofferStrube.Blazor.SVGEditor.Samples.csproj --configuration Release --output build

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/main' }} # Publish only when the push is on main
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: build/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
